name: credenciamento_toten
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cronet_http: ^1.3.2
  cupertino_http: ^1.5.1
  fetch_client: ^1.1.2
  http: ^1.2.2
  rive: ^0.13.13
  window_manager: ^0.4.2
  sqlite3: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-SemiBold.ttf

  uses-material-design: true
  assets:
    - assets/qrcode.riv
    - assets/images/simtec2024.webp
    - assets/images/simtec2024-2.webp